// dok_frontend/src/views/Products.vue
<template>
  <div id="app">
    <div class="notification" v-for="(product, i) in products" :key="product._id">
      <p>
        <span class="tag is-primary">{{i + 1}}</span>
        {{product.name}} {{"$" + product.price}}
      </p>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "product-s",
  data(){
    return{
      products:[],
    }
  },

  async mounted(){
    const res = await axios.get('http://localhost:3000/products')
    console.log(res.data.products)
    this.products = res.data.products;
  }
}
</script>

<style scoped>
#app{
  margin: auto;
  margin-top: 3rem;
  max-width: 700px;
}
</style>

// frontend/src/routes/products.svelte
<script>  
  const load = fetch("http://localhost:3000/products").then(res => res.json());
</script>

<svelte:head>
  <title>Products</title>
</svelte:head>

<h1>Products</h1>

{#await load then data}
  <div>
    {#each data.products as product}
      <p>{product.name} ${product.price}</p>
    {/each}
  </div>
{/await}
